# Generated by Django 3.1.1 on 2020-09-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contac',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождение'),
        ),
    ]
